ALTER TABLE public.items
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS created_by_admin_id UUID,
ADD COLUMN IF NOT EXISTS demo_purpose TEXT;

ALTER TABLE public.transactions
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS created_by_admin_id UUID;

ALTER TABLE public.ratings
ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.items SET is_demo = FALSE WHERE is_demo IS DISTINCT FROM FALSE;
UPDATE public.transactions SET is_demo = FALSE WHERE is_demo IS DISTINCT FROM FALSE;
UPDATE public.ratings SET is_demo = FALSE WHERE is_demo IS DISTINCT FROM FALSE;

ALTER TABLE public.items
ALTER COLUMN is_demo SET DEFAULT FALSE,
ALTER COLUMN is_demo SET NOT NULL;

ALTER TABLE public.transactions
ALTER COLUMN is_demo SET DEFAULT FALSE,
ALTER COLUMN is_demo SET NOT NULL;

ALTER TABLE public.ratings
ALTER COLUMN is_demo SET DEFAULT FALSE,
ALTER COLUMN is_demo SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_items_demo_status_created
ON public.items(is_demo, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_transactions_demo_status_created
ON public.transactions(is_demo, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ratings_demo_rated
ON public.ratings(is_demo, rated_id);

COMMENT ON COLUMN public.items.is_demo IS 'True for admin-created demo/screenshot listings. Demo items must be excluded from normal public surfaces.';
COMMENT ON COLUMN public.items.created_by_admin_id IS 'Admin user who created this demo item.';
COMMENT ON COLUMN public.items.demo_purpose IS 'Purpose for demo item: app_store_screenshot, flow_test, or other.';
COMMENT ON COLUMN public.transactions.is_demo IS 'True for demo transactions. Demo ratings and aggregate metrics should exclude these unless explicitly requested.';
COMMENT ON COLUMN public.ratings.is_demo IS 'True for ratings generated by demo transactions. Exclude from public rating aggregates.';

NOTIFY pgrst, 'reload schema';
